apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-2.2.2
  annotations:
    meta.helm.sh/release-name: kubecost
    meta.helm.sh/release-namespace: kubecost
rules:
  - apiGroups: [""]
    resources:
      - pods/log
      - pods
      - nodes
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
