apiVersion: v1
kind: Service
metadata:
  name: optikube-loadbalancer
  namespace: optikube-namespace
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: optikube