apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optikube-rolebinding
subjects:
- kind: ServiceAccount
  name: optikube-service-account
  namespace: optikube-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: optikube-role